### ISSUE TITLE
 Static Code Analysis

### ISSUE THREAD

**Issue by nagylev** [BME-MIT-IET/iet-hf-2022-idegtepo#3]
Analyze project with SonarLint

**Comment by tamarci** [comment]
Install SonarLint for PyCharm

**Comment by nagylev** [comment]
Fixed issues such as unused variables, code smelles, commendted codes.

Commits: 08a36c474af6909481b0edb82ba5d21b6964d2f6 2168f0bf28d89c371b34697a08a5338331076d73 ffcefe7bf6eadd230c0879af88df7f39364db007 5f66508bd5ad493860e58673841e4a312b55e47a fc4331d0d7013ab5f7086b873c1953072721074d 89d6826f0f8c23b6b0cc620886bdf2feb634cfd8 b96d2242bb1f9ff6b625a845db31e7520724a21b 9af673c82eba306b18afdf0b82385a598bb9790a 745e7c1970713f6fab3d305f9e041b0eb48f9cf0 0b3446e46ce699597b5fe97838af4e7cf06f7118

**Comment by nagylev** [comment]
Documented 

Commit: 77688fcaf546f7b33176fe17d21bd32ce46a6e1a
